name: CI
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build Binaries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Golang
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.5'
      - name: Build Book
        run: go build -o build/book cmd/book/main.go
      - name: Build Migrator
        run: go build -o build/migrator cmd/migrator/main.go
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Golang
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.5'
      - name: Functional Tests
        run: CONFIG_PATH=config/test.yaml LOG_MODE=silent go test ./tests -v --run _Functional



